/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package LinkedListProgram;

import org.junit.Test;
import static org.junit.Assert.*;

public class MyLinkedListTest {
   	
	@Test
	public void givenThreeNumbersShouldPassedLinkedListTestToTop()
	{
		MyNode<Integer> myFirstNode=new MyNode<>(70);
		MyNode<Integer> mySecondNode=new MyNode<>(30);
		MyNode<Integer> myThirdNode=new MyNode<>(56);
		MyLinkedList myLinkedList=new MyLinkedList();
		myLinkedList.add(myFirstNode);
		myLinkedList.add(mySecondNode);
		myLinkedList.add(myThirdNode);
		myLinkedList.printMyNodes();
		boolean result=myLinkedList.head.equals(myThirdNode) &&
					   myLinkedList.head.getNext().equals(mySecondNode) &&
					   myLinkedList.tail.equals(myFirstNode);
		assertTrue(result);
	}
}
